### PR TITLE
Fix #39 bloated docker and broken elm-build

### LINKED ISSUE #39: Docker image is bloated because of all the junk development files, and it does not create main.js
This ticket grew from a bug fix to an improvement, so I'll give estimate it

### PR DESCRIPTION
**Pull request by dimus**
* Remove production.rb and switch completely to docker_start.rb
* Fix docker_start to compile the elm code for production
* Clean puma.rb config to work in k8s environment
* Remove junk file by cleaning up and verifying .dockerignore
  This changed the size of the app dir significantly

There are still some problems with dockerfile we create.

1. We do need to make a production version that, because gcc and
other big packages blow the size of the image to 1G

2. Database creation does not work in production because postgres
send "not sufficient privileges error". We need to address it at
some point. For now I did comment `rake db:create` out for
production

### CODE REVIEW

File: exe/docker_startup.sh [hunk 1]
```diff
@@ -26,7 +26,7 @@ function development {
 function production {
   cd /app && npm run build && mkdir -p public/assets/js && mv dist/static/js/* public/assets/js
 
-  bundle exec rake db:create || true
+  # bundle exec rake db:create || true
```
Comment (joshuaclayton) [inline exe/docker_startup.sh]: should we delete this line entirely?

**Review by joshuaclayton — APPROVED** [review]
One minor comment; other than that, this looks good to me. I'm also excited to see image sizes reduced; I ran out of disk space earlier this week due to me playing around with Docker.

File: exe/docker_startup.sh (hunk 1 above)
Comment (dimus) [reply exe/docker_startup.sh]: I will delete it, we will need to make sure that production db can be created by docker compose in production environment. It should happen, as environment variable that triggers it is the same for kubernetes and docker compose
